jobs:
  NAME_HERE:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: Debug

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      working-directory: ./POCs/WiFi/Server/ # Pas dit aan naar jouw project folder
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
      working-directory: ./POCs/WiFi/Server/ # Pas dit aan naar jouw project folder
      run: cmake --build ./build --config ${{env.BUILD_TYPE}}
    
    - name: Test
      working-directory: ./POCs/WiFi/Server/ # Pas dit aan naar jouw project folder
      run: ctest -C ${{env.BUILD_TYPE}}
