name: CI

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason/Run name'
        required: true
        default: 'Manual trigger'

run-name: ${{ inputs.reason || github.event.pull_request.title || github.event.head_commit.message || 'unexpected workflow trigger' }}

jobs: 
  WiFI-POC:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: Debug

    steps:
    - uses: actions/checkout@v3
    
    # - name: Navigate
    #   run: cd ${{github.workspace}}/POCs/WiFi/Server/
    
    - name: configure
      working-directory: ./POCs/WiFi/Server/
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
      working-directory: ./POCs/WiFi/Server/
      run: cmake --build ./build --config ${{env.BUILD_TYPE}}
    
    # - name: Test
    #   working-directory: ${{github.workspace}}/POCs/WiFi/Server/build
    #   run: ctest -C ${{env.BUILD_TYPE}}
